version: '3.1'

services:
    app:
        image: openvidu/openvidu-insecure-js-screen-share-demo:2.20.0
        restart: on-failure
        network_mode: host
        environment:
            - OPENVIDU_URL=https://${DOMAIN_OR_PUBLIC_IP:-}:${HTTPS_PORT:-443}
            - OPENVIDU_SECRET=${OPENVIDU_SECRET}
